/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {

  namespace StencilComponents {
    interface TopAppBar {
      'background': string;
      'color': string;
      'firstName': string;
      'firstNameUrl': string;
      'secondName': string;
    }
  }

  interface HTMLTopAppBarElement extends StencilComponents.TopAppBar, HTMLStencilElement {}

  var HTMLTopAppBarElement: {
    prototype: HTMLTopAppBarElement;
    new (): HTMLTopAppBarElement;
  };
  interface HTMLElementTagNameMap {
    'top-app-bar': HTMLTopAppBarElement;
  }
  interface ElementTagNameMap {
    'top-app-bar': HTMLTopAppBarElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'top-app-bar': JSXElements.TopAppBarAttributes;
    }
  }
  namespace JSXElements {
    export interface TopAppBarAttributes extends HTMLAttributes {
      'background'?: string;
      'color'?: string;
      'firstName'?: string;
      'firstNameUrl'?: string;
      'secondName'?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }

export declare function defineCustomElements(window: any): void;